name: form_builder_map_field
description: Location Input Field for flutter_form_builder package. Used to select coodinates on a map.
version: 1.0.0-alpha.1
homepage: https://github.com/danvick/form_builder_map_field

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.3.1
  google_maps_flutter: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
